### ISSUE TITLE
Replace configuration loading

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1522]
Currently phpDocumentor uses JMS Serializer to load the template and configuration files for phpDocumentor but this introduces a number of dependencies that are otherwise not used. In order to reduce the number of dependencies I want to replace this with either a simpler component or a custom-written loader to reduce any dependencies at all

This is the first step in removing JMS Serializer; once the loading of the Templates is implemented as well we can remove JMS Serializer.

With phpDocumentor 3 we want to be able to load an XML (no other format; no foreseeable need for other formats and only adds complexity) and return an array of strings containing a normalized form of the configuration settings.

It is important to note that the ConfigurationFactory receives a URI and should be able to load a configuration file over HTTP so that people can directly refer to a config file on Github and that phpDocumentor checks out everything using the settings in the Configuration file.

Another important note is that the Configuration format should change for phpDocumentor 3 but we want the ConfigurationFactory to load phpDocumentor 2 based configuration files as well. So the Factory needs to detect which type of Configuration file it is loading, load the file and output a uniform array with settings. When we load the phpDocumentor 3 configuration we should also verify the XML format using an XSD.

Steps:

- [ ] Write a Factory that maps an array directly from XML configuration files to
    - [ ] Support the phpDocumentor 2 configuration file
    - [ ] Support the new phpDocumentor 3 configuration 
- [ ] Replace the retrieval of the configuration with this Factory
- [ ] Remove the Configuration classes
- [ ] Create an XSD to verify the phpDocumentor 3 format

**Class diagram**

![](http://www.plantuml.com:80/plantuml/png/RO-z2W8n383tFaK6XnxY2xWAWk0atAHob5nj2xr4cdGGyTsjte6BMKBoVUG7inE17TCjXLgS9gQzG-NoWAU15ciO1cGIBHNLzYN1AZD-nLPqYrFyFJlqnuNCNltnuDLsi8Ks9b4uNytB4Ak7aaBKrf-vHAvv17GO6_9IimeaWibFxQ0BEO7C5A3b_dI09509ewFWHsC-Asst-VkBUGC0)

As mentioned in the task listing should we want to support both the phpDocumentor 2 and phpDocumentor 3 configuration formats where we normalize both into the same array based on the new phpDocumentor 3 configuration format.

An example of the new Configuration file should look similar to this:

```xml
<?xml version="1.0" encoding="utf-8"?>

<phpdocumentor
    version="3"
    xmlns="http://www.phpdoc.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.phpdoc.org phpdoc.xsd"
>
    <paths>
        <output>file://build/docs</output>
        <cache>/tmp/phpdoc-doc-cache</cache>
    </paths>
    <version number="1.0.0">
        <output>latest</output>
        <api format="php">
            <dsn>file://.</dsn>
            <path>src</path>
            <ignore>src/ServiceDefinitions.php</ignore>
     <ignore-hidden>true</ignore-hidden>
     <ignore-symlinks>true</ignore-symlinks>
     <extension>php</extension>
     <visibility>public</visibility>
        </api>
        <guide format="rst">
            <dsn>file://../phpDocumentor/phpDocumentor2</dsn>
            <path>docs</path>
        </guide>
    </version>
    <template name="clean"/>
    <template location="https://github.com/phpDocumentor/phpDocumentor2/tree/develop/data/templates/clean"/>
</phpdocumentor>
```

**Comment by mvriel** [comment]
Perhaps we should not load it into a generic configuration object but re-use the DIC to supply the config for individual components

**Comment by mvriel** [comment]
This was finished
