### ISSUE TITLE
Add support for reference documentation

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1527]
One of the main features for phpDocumentor 3 should be that it can support your complete documentation toolchain from start to end. The biggest feature that is missing is the support for generating reference documentation.

There are other tools out there that do a similar job, but with phpDocumentor we want to focus on that complete experience.

In order to achieve this we should:

- [ ] Support generating documentation from Restructured Text
- [ ] Support generating documentation from Markdown (CommonMark variant)
- [ ] Be able to divide documentation in Books (for example Symfony has The Book, The Cookbook and a book for each component)
- [ ] Have support for the same book in multiple languages
- [ ] Be able to generate documentation for multiple versions of the same project
- [ ] Configure which Books and Versions in the configuration (not the command line; too much info for the command line)
- [ ] Use Git(hub) as a source to load Books and Versions from (#1500)

Currently the new configuration file format that I am considering is:

```
<?xml version="1.0" encoding="UTF-8" ?>

<phpdocumentor version="3">
    <title>Documentation</title>
    <language>en</language>
    <target>build/docs</target>
    <cache-path>{{target}}/.cache</cache-path>

    <files ignore-hidden="true" ignore-symlinks="true">
        <encoding>utf-8</encoding>
        <directory>.</directory>
    </files>

    <book title="Documentation" language="en">
        <files>
            <directory>docs</directory>
        </files>
    </book>

    <api>
        <default-package-name>Default</default-package-name>
        <markers>
            <item>TODO</item>
            <item>FIXME</item>
        </markers>
        <extensions>
            <extension>php</extension>
            <extension>php3</extension>
            <extension>phtml</extension>
        </extensions>
        <visibility>public</visibility>
        <files>
            <directory>src</directory>
        </files>
    </api>

    <template name="clean"/>

    <version name="latest"></version>
    <version name="2.x">
        <files>
            <directory>github:repo=phpDocumentor/phpDocumentor2;branch=master</directory>
        </files>
    </version>
</phpdocumentor>
```

The version number in the root node indicates how to load the configuration and will allow us to switch between formats between major versions while keeping backwards compatibility

**Comment by mvriel** [comment]
This issue will be replaced by another based on research that we have done in the past period of time
