### ISSUE TITLE
[!] Refactor architecture

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1552]
During a sabbatical from phpDocumentor I got thinking that phpDocumentor 2 was too change resistant was because it was architected for too much flexibility and compartmentalised into illogical divisions.

> An example of the latter was the way the transformer worked; you need to be in the `phpDocumentor\Transformer`, `phpDocumentor\Compiler` and parts of the `phpDocumentor\Plugin\Core` namespaces. Anyone with knowledge of the architecture would figure this out but it makes it harder for those that don't: the most people

An additional issue was that the [UBIQUITOUS LANGUAGE](http://martinfowler.com/bliki/UbiquitousLanguage.html) was lacking in clarity and was also not properly expressed in the domain of phpDocumentor. 

As a thought experiment I did a [partial re-implementation of phpDocumentor](https://github.com/mvriel/phpDocumentorXP) if I would have done a complete rewrite. Although part of me would want to finish the greenfield implementation and replace the current version of phpDocumentor with it this would not be convenient as a lot of business rules would be lost and a long time would pass until phpDocumentor 3 is available.

What this basically comes down to is that we apply some concepts from DDD and clearly define 3 aggregates:

**Documentation**
![documentation](https://cloud.githubusercontent.com/assets/193704/7595346/b7dd5f40-f8e6-11e4-9a94-20f3d360722a.png)

**Definition**
![version-definition](https://cloud.githubusercontent.com/assets/193704/7595347/b7de0986-f8e6-11e4-8ac3-260968a717d5.png)

And undiagrammed: the **Template** aggregate.

In addition we want to make use of a more clear UBIQUITOUS LANGUAGE, including the use of DDD concepts such as REPOSITORIES and FACTORIES.

We identify the following concepts at the moment:

```
Definition

Documentation
    Project
        A Project is a series of Documentation spanning multiple versions where each version refers to the same undertaking.
        Examples of a project can be a Software Project, such as phpDocumentor_, or the authoring of a Book or standalone
    reference, such as PSR-5_.

        phpDocumentor does not actively track a Project but instead assumes that all Versions that are defined in the configuration belong to the same project.

    Version
        A Version of a Project represents a unique series of files that can be transformed into a set of Documentation. It
    is not necessary for the locations of Document Groups to be on the same Data Source as sometimes manuals and source
    files are located on different locations.

    > For example: the source files used to generate an Api Reference may be in a different VCS repository than the
    > source files for the User Manual for the same Version

    Documentation

    Document Group
        A set of Documentation can include several multiple Guides, Api References and similar objects. Such an object is
    called a Document Group as it combines into a logical grouping and offers the option to add new Document Groups
    in the future should the need arise.

Guides
    Guide
    Guide Language
    Document
    Translation
    Chapter
API Documentation
    Api Reference
    Api Language
    Fqsen
    Element
    PHP
        Visibility
        Namespace
        Constant
        Function
        Class
        Interface
        Trait
        Class constant
        Property
        Method
        DocBlock
        Summary
        Description
        Tag
Rendering
    View
    Renderer
    RenderAction
    Template
```
> not all terms are provided with more information; this may be added upon later if needed

This is a significant effort that will allow phpDocumentor to grow and also to help people get acquinted with phpDocumentor. I have identified the following areas that need to be addressed but I am confident more will show during the refactoring process and these should be added to the list below:

- [x] Add the Version Entity and VersionNumber Value Object
- [x] Add the Documentation Entity and DocumentGroup Value Object
- [x] Route file access via FlySystem
- [x] Add the FlyFinder plugin so that we have access to the new Finder
- [x] Add all specifications that are in place now (not all are implemented yet)
- [x] Add the Definition Aggregate and move as much of the configuration options there
- [x] Replace the Transformer with the Renderer and Writers with RenderActions

**Comment by TomasVotruba** [comment]
This looks great :+1:

**Comment by mvriel** [comment]
Thanks @TomasVotruba!

**Comment by mvriel** [comment]
Closing this issue as most of the moving parts have been implemented or are being implemented; I will create new issues to specifically address points that still need to be done
