### ISSUE TITLE
Refactor Parser to the Documentation Foundation

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1553]
> This issue is part of / related to #1552 

I will be replacing the issue description with a more suitable text

- [x] Implement caching of the Documentation aggregates in the DocumentationRepository
- [x] Replace loading of files using the Fileset component with FlySystem and the new FlyFinder plugin
- [x] Parse file contents using the new DocumentationFactory rather than via the current Parser
- [x] In every location where the ProjectDescriptor is retrieved from the Analyzer, retrieve the Documentation using the Documentation Repository
- [x] Replace usage of the phpDocumentor\Dispatcher with the new League/Event messages of the Reflection package and thus make the Event folder obsolete
- [x] Ensure that all functionality from the Parser folder is re-implemented in the new architecture and that the contents of the folder are then removed

**Comment by mvriel** [comment]
@jaapio I tried to be as complete as I could be in this morning; can you review this text to see if it makes sense? I will review this again tonight and see what I missed

**Comment by jaapio** [comment]
I'm working in this one

**Comment by mvriel** [comment]
This item has been completed; a QA step needs to be done to verify all steps but this will be done as part of a centralized QA effort
