### ISSUE TITLE
Replace Cilex with PHP-DI 5

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1559]
Currently the Application class works as a Dependency Injection Container based on Pimple; what we want is to replace Pimple with PHP-DI 5 as the latter offers auto-wiring and makes service definitions a lot smaller.

It is expected that this change will also reduce the number of dependencies and thus make for a smaller and simpler application.

- [x] Do not extend Application class from Cilex
- [x] Add PHP-DI 5 (currently on master) to the composer.json
- [x] Add Symfony Console to the composer.json (as it is no longer imported with Cilex)
- [x] Remove Cilex from the composer.json
- [x] Create a Service Definition file for PHP-DI (http://php-di.org/news/14-php-di-5-syntaxic-sugar.html)
- [x] Rewrite all Service Providers into that Service Definition (not all services need to be copied since PHP-DI uses autowiring)
- [x] Initialize PHP-DI from the Bootstrap and inject it into the Application class
