### ISSUE TITLE
Documentation Standards in phpDocumentor 3

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1599]
> _Important:_ this item should be developed against the develop branch and not the master branch; the develop branch contains all parts needed for phpDocumentor 3 where master does not.

The basic idea behind this feature is that we want to be able to check a codebase that has been parsed by the phpDocumentor Reflection package against a Documentation Standard, and receive a list of violations of that Standard so that developers can ensure consistency in their project and make sure their documentation is in order.

The Reflection package of phpDocumentor will analyse the source code of an entire project and create an object graph representing all elements of that project including their associated Documentation (using DocBlocks).

This object graph starts with a phpDocumentor\Reflection\Project object, which in turn consists of a series of objects representing Files and in those files is a tree of elements in those files.

This feature should accept any element in that tree (project, file, class, etc) and recursively check those elements against a Documentation Standard. A Documentation Standard will contains a series of rules and settings for those rules; if an element is applicable for a rule, such as a check on `@return` on a Method, but fails the rules business logic then a Violation should be emitted.

After one or more elements are checked should we have a list of violations of which we know at least:
1. Which element the violation happened on, identified by their FQSEN
2. What the severity of the violation is
3. A code identifying the rule
4. A (configurable) message 
## Acceptance Criteria
- [ ] It should be possible to define Documentation Standards that consist of a series of preconfigured rules
- [ ] It should be possible to extend or import Documentation Standards in a Documentation Standard and disable one or more rules, or adjust one or more parameters of rules
- [ ] Each rule should represent a single violation of the Documentation Standards, see below for an initial list of rules
- [ ] Every rule may have a severity associated with it, this represents if the rule is an error, warning or notice. 
- [ ] The default severity of a Rule may be overridden
- [ ] Every rule has a default message associated with it
- [ ] The default message of a rule may be overridden
- [ ] A rule can be limited to a specific set of Elements. For example: checks on the `@return` tag are only allowed for functions and methods
- [ ] After the verification is completed a list of violations should be returned with at least 
- [ ] Test covered
## Technical Guidelines
- The description of this item states that we want to check Reflected information; this is true for this specific item but we will want to re-use this component to verify all documentation interpreted by phpDocumentor; this might be a design consideration.
- This item relies on functionality of the Reflection component that is being developed on its develop branch and differs from the last tagged release. For example: with the new Reflection Component you have a DocBlock object associated with elements supporting a DocBlock, previously the DocBlock properties were integrated into the Element.
- Part of the challenge of this item is that development on the Reflection component is not complete yet; you will probably (partially) rely on mocks to test this feature.
- Rules and Rulesets should match the style or intent of PHP_CodeSniffer so we can reuse its XML configuration format
- Based on, at least basic, DDD concepts
- Should be able to pass a Project or individual element to be checked
- If an element is checked that contains other children that can be checked, it should recursively verify every element 
- If needed, a CommandBus is allowed but the Tactician package should be used because we are going to use that in other parts of the application as well
## Rules
1. Files should have a summary (may be a specific one, should be configurable)
2. Files should have a description (may be a specific one, should be configurable)
3. Files should have [configurable] tag(s); for example: copyright, author, etc
4. All classes should have a Summary
5. All methods should have a Summary
6. The typehint of a method or function should match that of the `@param` property in the DocBlock; if the Typehint and `@param` type are both an FQSEN then we should accept it since the Typehint may describe an interface and the DocBlock a concrete instance
7. All methods should have [configurable] tags; for example: return tags on methods

More rules will be added before the start of the event or after the event if this item is still under development

**Comment by mvriel** [comment]
Closing the 3.0 tickets, will reconsider them after our re-alignment
