### ISSUE TITLE
Replace Transformer and Compiler with Renderer, View and View Filters

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1633]
# Replace Transformer and Compiler with Renderer, Views and View Filters

The goal of this improvement is to replace the old Transformer and Compiler classes with the new Renderer architecture. 

Once the RenderCommand is invoked phpDocumentor will iterate through each Documentation Version and for every Version subsequently apply each Render Action to that Documentation Version. A Render Action always has one or more Views of the Documentation Version with which it can interact. A View consists of base data that is augmented by a series of filters (that can be defined).

For example:

> To render the list of all classes in a Documentation Version there may be a view called Classes. This view may return an array of class names by scanning the Documentation Version’s API DocumentGroups for all elements of type Class_ and compiling an array with those names.
## Retrieving the data for a view

Views are identified by their name and type; the name is, or can be, used as an identifier in a template to refer to that view (for example the name ‘project’ is currently used in some twig templates). The type of a view will determine which View Mapper is used to create the ‘base data'. A View Mapper is responsible for extracting an array with this base data from the Documentation Version. After a View Mapper has extracted this information the ‘base data’ may be augmented by a series of filters that can remove, extract or alter information in the ‘base data’.

For example:

> To have a backwards compatible View for phpDocumentor 2 we want to have a View Type ‘phpDocumentor2Project’; this type will map onto a View Mapper ‘phpDocumentor2Project’ that iterates through all API DocumentGroups in a Documentation Version and creates an array out of that that will match the structure of the Project Descriptor and its Descriptor Children of phpDocumentor 2 so that the current templates can be re-used unaltered. Because the data needs to be transformed using a series of 
> steps that were previously compiler passes we need to have a series of filters specific to this View Type that will deal with the same things as the Compiler Passes. (Note: these may also be handled directly in the View Mapper if that saves performance).

Another example of using a filter:

> For the Twig and XSL Render Actions you can provide a filter that will only extract part of the ‘base data’; using the Pathfinder class it can locate a specific node in the base data and return just that node; meaning that the rest of the base data is discarded.
## Caching

Because the mapping of base data can be costly and is possibly repeatedly done we should investigate if it is advantageous, in terms of memory and performance, to cache the results of a View Mapper to disk or other external storage.
## Tasks
- [ ] Change Filters to use a Message -> Handler based system so that Filter handlers can have dependencies of their own and the FilterMessages can be instantiated during the instantiation of a View
- [ ] Refactor \phpDocumentor\Compiler\Linker into a Filter so that it can be used as part of a view
- [ ] Refactor \phpDocumentor\Compiler\Pass\ExampleTagsEnricher into a Filter so that it can be used as part of a view
- [ ] Refactor \phpDocumentor\Compiler\Pass\ElementsIndexBuilder into a Filter so that it can be used as part of a view
- [ ] Refactor \phpDocumentor\Compiler\Pass\MarkerFromTagExtractor into a Filter so that it can be used as part of a view
- [ ] Refactor \phpDocumentor\Compiler\NamespaceTreeBuilder into a Filter so that it can be used as part of a view
- [ ] Refactor \phpDocumentor\Compiler\PackageTreeBuilder into a Filter so that it can be used as part of a view
- [ ] Refactor \phpDocumentor\Compiler\Pass\ResolveInlineLinkAndSeeTags into a Filter so that it can be used as part of a view
- [ ] The pre-existing templates should, without changes to the template itself, use the new views functionality with all of the above filters applied
- [ ] New templates should be able to select which views to use
- [ ] Investigate whether caching of base data is worth it and if so, implement it

**Comment by mvriel** [comment]
The basic architecture is implemented aside from a caching ViewRepository; this is my next goal

**Comment by mvriel** [comment]
Closing the 3.0 tickets, will reconsider them after our re-alignment
