### ISSUE TITLE
Reintegrate Plugins and remove support

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1635]
With phpDocumentor 3 we have replaced Cilex with a bare version of the Symfony Console Application and PHP-DI. This breaks how plugins currently work but plugins didn’t see a high adoption rate so we can remove support for this to clean up the codebase. In a future version we might re-add plugin support if there is enough demand.
## Tasks
- [ ] Convert LegacyNamespaceFilter to a View Filter and remove plugin
- [ ] After validation has been reworked, remove the Plugin\Core\Descriptor
- [ ] Remove the Plugin and Parameter classes
- [ ] Remove plugin loading from Application class

**Comment by mvriel** [comment]
Closing the 3.0 tickets, will reconsider them after our re-alignment
