### ISSUE TITLE
phpDocumentor 3 post-refactoring clean up

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1636]
We try to minimise the amount of code that is needed to make the application run and part of that is a refactoring run to clean some things up. This may have dependencies on other issues as well so we should be careful not to start on this too soon.
## Tasks
- [ ] Refactor Bootstrap.php away
- [ ] Remove ensureAnnotationsAreCached method from Application.php once all annotations have left the application
- [ ] Move initialization code to bin/phpdoc from Application.php en move remaining code (if any) to Application/Console.php
- [ ] Investigate if with an architectural change we can get rid of the RenderPass; it feels like it is introducing unneccesary coupling

**Comment by mvriel** [comment]
Closing the 3.0 tickets, will reconsider them after our re-alignment
