### ISSUE TITLE
phpDocumentor 3 post-refactoring QA

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1637]
After all steps for refactoring the phpDocumentor 2 architecture to phpDocumentor 3 have completed we should have an exhaustive QA effort to discern where information is missing or still broken.

It should be mentioned that resolving any issues that arise from this QA session is not included in the scope for this issue; if bugs are found they should be reported separately.
## Tasks

The following activities have been identified as part of this effort:
- [ ] Perform a functional test with various encodings, including Russian and Chinese
- [ ] Check Unit test Coverage and repair any broken or incomplete tests
- [ ] Audit the codebase that a Flysystem Filesystem is used throughout the system for input, and another one for the output
- [ ] Profile the application using blackfire.io and create issues for each bottleneck found
- [ ] Check if the Vagrant development machine still provisions and ups without issues
- [ ] Test if a PHAR archive can be built and runs without issues
- [ ] Perform an analysis of the new architecture after all old components have been removed and check to see where it requires more cleaning to make it neat
- [ ] Check existing documentation for correctness and make a list of missing subjects

**Comment by mvriel** [comment]
Closing the 3.0 tickets, will reconsider them after our re-alignment
