### ISSUE TITLE
Research and create a base Template and change existing templates to use that

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1639]
Currently each template has its own twig or xsl file used to generate the representation of a structural element. This is however inconvenient as it will increase maintenance severely. A point of investigation is whether we can create a common series of twig template files that contain fine-grained blocks that act as a template of templates.

This way we can have, for example, a class block that will generate the same results for each template but that can be overridden specific for a template.
## Tasks
- [ ] Make a list of fine-grained blocks in the existing templates
- [ ] Research how to make block layouts that can be overridden in specific templates (starting point: http://twig.sensiolabs.org/doc/tags/embed.html) without having to override the individual blocks
- [ ] Create / extract these blocks and place them in a special folder in /data and add that to the template folders as first one
- [ ] Create a version of the Responsive-Twig template based on this
- [ ] Create a version of the clean template based on this

**Comment by mvriel** [comment]
Closing the 3.0 tickets, will reconsider them after our re-alignment
