### ISSUE TITLE
Allow Render Actions to influence the menu in templates

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1640]
> this item is related to the base template feature in #1639 and these efforts could be collaborated on

Not every template uses the same render actions, when you omit the Class Diagram render action you should not see the menu item for the Class Diagram in the template.

In order to work this out we want for Render Actions to be able to influence the menu by adding new items to the main menu bar or to a sub item in that main menu. Originally I thought this could be done by adding specific blocks to the twig template but this will not work when you want to add a submenu item.

This means that we need a MenuBuilder with which we can add, remove or change a menu by adding top level items and possibly sub items for each top level item. This menu should be capable of being included as a Twig block in a template.

The goal for this item is to make a menu more flexible and when using multiple templates they should share the same menu with all their items combined. This probably means that the menu items need to be collected before the actual rendering takes place because otherwise it may occur that the menu differs per generated resource.

## Tasks

- [ ] Research how to best generate URLs for use in the menu
- [ ] Create Menu Builder component with which you can add a Menu Item
- [ ] Allow a Menu Item to have sub items, A menu item can have the following properties
    -  label
    - url
- [ ] Create a series of Twig blocks where a menu can be inserted into another layout
    > Please ensure that it has fine-grained blocks so that individual templates can override the blocks for template-specific styling
- [ ] Adjust the common template of #1639 to include this menu
- [ ] Check and adjust the Clean template
- [ ] Check and adjust the Responsive template
